version: '2'
services:
    servicesusuariogorilas-app:
        image: servicesusuariogorilas
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://servicesusuariogorilas-postgresql:5432/servicesUsuarioGorilas
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    servicesusuariogorilas-postgresql:
        extends:
            file: postgresql.yml
            service: servicesusuariogorilas-postgresql
