version: '2'
services:
    servicesusuariogorilas-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/servicesUsuarioGorilas/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=servicesUsuarioGorilas
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
